== Configuration Model for "Key Data"
Key data are data which identifies an object. For example a person vertex with personal
attributes like name, last-name, address, email, birthdate ... has one or more attributes
which defines the identity of this object. In our case the "email" would be the attribute.

Other data will reference a person by there email. In this case the "email" attribute is a
"key data" attribute. When exporting the graph data to independent files the email is the field
connecting them. So the email must be known on both sides.

As this TDG should be able to create mass data it is important to reduce the amount of data
to be stored in RAM. That the reason why these key data will be created up front. While
all the other attributes which are not needed for connection data will be created on the
fly while exporting the record.


The following example is the top level of the configuration file.

.Example top level
[source,js]
----
{
  "configs": {},  <1>
}
----
<1> Under this key the all the key data configuration is stored.


The next example shows the definition for one single vertex.

.Example vertex
[source,js]
----
{
  "application": {													<1>
    "tdg": {                                <2>
      "id_fields": {                        <3>
        "app_id": {                         <4>
          "type": "regex",                  <5>
          "exp": "[1-9]{1,3}-[a-z]{3,8}",   <6>
          "case_sensitive": true,           <7>
          "unique": true                    <8>
        }
      }
    }
  }
}
----
<1> The name of this vertex the key data to create for.
<2> The TDG section. Contains all the fields to be created as key data.
<3> The key data fields section.
<4> The name of the key data field.
<5> The type of the generator to use to create the data. In this case the
reverse regular expression generator.
<6> An attribute used be the generator. In this case the regex to create the data
<7> An attribute used be the generator.
<8> Should the generated data be unique. As we are in the key data section
this would be true in most of the cases.
